name:                toy-tsp-solver
version:             0.1.0.0
homepage:            https://github.com/gokuld/toy-tsp-solver#readme
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - random

executables:
  toy-tsp-solver:
    source-dirs:      src
    main:             Main.hs
